secret_santa_app/templates/views.py
from flask import Blueprint, flash, make_response, redirect, render_template, request, url_for
from loguru import logger

from secret_santa_app import db

# start application definitions
main = Blueprint("main", __name__)


# define routes
@main.route("/", methods=["POST", "GET"])
def index():
    return render_template("home.html", title="Welcome to BestSecret Santa!")

secret_santa_app/users/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from flask_wtf.csrf import ValidationError, validate_csrf
from loguru import logger
from werkzeug.security import check_password_hash, generate_password_hash

from secret_santa_app import db
from secret_santa_app.models import Address, User
from secret_santa_app.users.forms import UserCreateForm, UserDeleteForm, UserEditForm

users = Blueprint("users", __name__, template_folder="templates")


# Routes for handling user specific pages
@users.route("/")
@login_required
def profile():
    return render_template("users/index.html", title=f"Hello {current_user.name}!")


@users.route("/create")
def signup():
    user_form = UserCreateForm()
    return render_template("users/signup.html", form=user_form)


@users.route("/create", methods=["POST"])
def signup_post():
    email = str.lower(request.form.get("email"))
    user = User.query.filter_by(email=email).first()
    if user:
        flash("Email address already exists", "is-warning")
        return redirect(url_for("users.signup"))

    user_form = UserCreateForm(request.form)
    if user_form.validate():
        new_address = Address(description=request.form.get("address"))

        new_user = User(
            name=request.form.get("name"),
            email=str.lower(request.form.get("email")),
            password=generate_password_hash(request.form.get("password"), method="sha256"),
            address=new_address,
        )

        # add the new user to the database
        db.session.add(new_user)
        db.session.add(new_address)
        db.session.commit()

        flash("Successfully created user. Please log in!", "is-success")
        return redirect(url_for("auth.login"))
    else:
        flash("Couldn't create user. Please check the inputs!", "is-warning")
        return render_template("users/signup.html", form=user_form)


@users.route("/edit", methods=["GET"])
@login_required
def edit():
    logger.warning(f"id: {current_user.id}")
    found_user = User.query.get(current_user.id)
    # prefill edit form
    form = UserEditForm(obj=found_user)
    return render_template("users/user_edit.html", user=found_user, form=form)


@users.route("/edit", methods=["POST"])
@login_required
def edit_post():
    user = User.query.get(current_user.id)
    form = UserEditForm(request.form)
    # from IPython import embed; embed()
    if form.validate():
        # normal edit logic
        user.name = form.data["name"]
        user.email = str.lower(form.data["email"])

        address = Address().query.filter_by(user_id=user.id).first()
        address.description = form.address.data
        user.address = address
        db.session.add(user)
        db.session.add(address)
        db.session.commit()
        flash("Edited Successfully!", "is-success")
        return redirect(url_for("users.profile"))
    else:
        # if we fail to edit, show the edit page again with error messages and values that the user has typed in!
        flash("Could not edit user!", "is-danger")
        return render_template("users/user_edit.html", user=user, address=user.address, form=form)


@users.route("/delete", methods=["GET"])
def delete_get():
    found_user = User.query.get(current_user.id)
    flash(f"You are about do delete user {found_user.name}. Are you sure ?", "is-danger")
    return render_template("users/user_delete.html", found_user=found_user)


@users.route("/delete", methods=["POST"])
@login_required
def delete_post():
    delete_form = UserDeleteForm(request.form)
    delete_user = User.query.get(request.form.get("user_id"))
    addresses = Address.query.filter_by(user_id=delete_user.id).all()
    if delete_form.validate():
        try:
            for address in addresses:
                db.session.delete(address)
            db.session.delete(delete_user)
            db.session.commit()
            flash("User Deleted along with all their addresses", "is-success")
            return render_template("home.html")

        except ValidationError:  # if someome tampers with the CSRF token when we delete an owner
            flash("Cannot delete user", "is-critical")
            return render_template("home.html")

secret_santa_app/templates/home.html
{% extends "main.html" %}
{% block content %}
{% endblock %}

secret_santa_app/templates/main.html
<!DOCTYPE html>
<html>
    <div class="snow"></div>
    <header>
        <title>Hello Santa!</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    </header>
    <body>
        <nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
            <div class="container">
                <div id="navbarMenuHeroA" class="navbar-menu">
                    <a href="   {{ url_for('main.index') }}" class=" navbar-item">
                        <span class="icon">
                            <i class="fas fa-home"></i>
                        </span>
                        Home
                    </a>
                    <a href="{{ url_for('groups.index') }}" class="navbar-item">
                        Groups
                    </a>
                    <a href="https://github.com/burningskies42" class="navbar-item">
                        Contact me
                    </a>

                    <div class="navbar-item navbar-end dropdown is-hoverable">
                        {% if current_user.is_authenticated %}
                        <div class="dropdown-trigger">
                            <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
                            <span>{{current_user.name}}</span>
                            <span class="icon is-small">
                                <i class="fas fa-angle-down" aria-hidden="true"></i>
                            </span>
                            </button>
                        </div>
                        <div class="dropdown-menu" id="dropdown-menu" role="menu">
                            <div class="dropdown-content">
                                <a href="{{ url_for('users.profile') }}" class="dropdown-item">
                                    Profile
                                </a>
                                <a href="{{ url_for('users.edit') }}" class="dropdown-item">
                                    Settings
                                </a>
                                <hr class="dropdown-divider">
                                <a href="{{ url_for('auth.logout') }}" class="dropdown-item">
                                    Logout
                                </a>
                            </div>
                        </div>
                        {% else %}
                        <div class="dropdown-trigger">
                            <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
                            <i class="fas fa-user"></i>
                            <span>Login / Register</span>
                            <span class="icon is-small">
                                <i class="fas fa-angle-down" aria-hidden="true"></i>
                            </span>
                            </button>
                        </div>
                        <div class="dropdown-menu" id="dropdown-menu" role="menu">
                            <div class="dropdown-content">
                                <a href="{{ url_for('users.signup') }}" class="dropdown-item">
                                    Register
                                </a>
                                <hr class="dropdown-divider">
                                <a href="{{ url_for('auth.login') }}" class="dropdown-item">
                                    Login
                                </a>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        <div class="content-wrap">
            <div class="container">
                <h2 class="title">{{title}}</h2>
                {% with messages = get_flashed_messages(with_categories=true) %}
                <br>
                {% if messages %}
                {% for category, message in messages %}
                <div class="notification {{ category }} is-light">
                    <button class="delete"></button>
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
        </div>
        <footer class="footer">
            <div class="content has-text-centered">
                <p>&copy; 2020 BurningSkies_1337 GmbH</p>
            </div>
        </footer>
        <script src="{{ url_for('static', filename='javascript/BulmaJS-0.12.0/dist/bulma.js') }}"></script>
    </body>
</html>